import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#080a0f] text-white px-6 py-16 max-w-2xl mx-auto">
      <Link href="/" className="text-[#7F77DD] text-xs hover:underline mb-8 block">← Back to PathForge</Link>
      <h1 className="text-2xl font-medium mb-2">Terms of service</h1>
      <p className="text-[#888780] text-xs mb-10">Last updated: January 2025</p>

      <div className="space-y-8 text-sm text-[#B4B2A9] leading-relaxed">
        <div>
          <h2 className="text-white font-medium mb-2">Using PathForge</h2>
          <p>PathForge is a free career guidance platform for students and graduates. By creating an account you agree to use the platform honestly and not attempt to misuse or disrupt the service.</p>
        </div>
        <div>
          <h2 className="text-white font-medium mb-2">AI-generated content</h2>
          <p>Career roadmaps, match scores, and mentor responses are generated by AI and are for guidance purposes only. PathForge does not guarantee employment outcomes or the accuracy of any AI-generated content. Always verify important information independently.</p>
        </div>
        <div>
          <h2 className="text-white font-medium mb-2">Your account</h2>
          <p>You are responsible for maintaining the security of your account. PathForge is not liable for any loss resulting from unauthorized access to your account.</p>
        </div>
        <div>
          <h2 className="text-white font-medium mb-2">Intellectual property</h2>
          <p>The PathForge platform, branding, and underlying technology are owned by PathForge. You retain ownership of any personal information you provide.</p>
        </div>
        <div>
          <h2 className="text-white font-medium mb-2">Changes to terms</h2>
          <p>We may update these terms from time to time. Continued use of PathForge after changes constitutes acceptance of the updated terms.</p>
        </div>
        <div>
          <h2 className="text-white font-medium mb-2">Contact</h2>
          <p>For any questions about these terms, reach us at hello@pathforge.app.</p>
        </div>
      </div>
    </div>
  );
}